### ISSUE TITLE
How to build these?

### ISSUE THREAD

**Issue by MaxBittker** [nunocorreia/MultitouchInteraction#1]
Hi Nuno - 

I'm TAing an open frameworks class at the school for poetic computation.

I came across your course while researching up to date information on running ofx iOS apps. 

Is there any existing documentation or information on how I can try these examples out :-)? 

Even if not, thanks for sharing these, the class sounds really great! - Max

**Comment by nunocorreia** [comment]
Hi Max,

Thanks for reaching out, and glad you found the examples useful! I've been teaching iOS with oF for 10 years now at Aalto University, it's been fun! Unfortunately I don't have any explanation / tutorial for those examples. I should build those... Some videos of projects done with students: https://vimeo.com/showcase/7366086

I am preparing video tutorials for another oF course I teach: https://github.com/aalto-mediacode/GenerativeMediaCoding2020, as I'm teaching that online due to COVID-19, maybe that could be useful for you.

Maybe we could think of ways to exchange more info / materials.

Cheers,
Nuno

**Comment by MaxBittker** [comment]
I was making a big mistake of using the osx openframeworks, and not the ios one. Now able to build & test your examples! (side note, the project generator wasn't updating them for me, I had to copy and paste the three files into a fresh project, but it works 😄) 

I am actually designing a fall curriculum right now related to mobile prototyping - if you would ever want to chat, my email is maxbittker@gmail.com! I'm really loving the framing of your course & the student work, so it would be really nice to talk.

**Comment by nunocorreia** [comment]
Hi Max,

Glad it's working out! Sure, if you're interested in chatting we can set a set up a chat. My email: mail@nunocorreia.com. I'm quite busy this week, but otherwise should be fine.
